model:
  name: networks.geocalib_pretrained_rays
  camera_model: simple_radial
  model_weights: distorted
data:
  im_geom_transform: null
  preprocessing:
    resize: null
    edge_divisible_by: null
  cam_id: radial:1
